name: STCCD
channels:
  - pytorch
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - abseil-cpp=20230802.0=h6a678d5_2
  - absl-py=1.4.0=py39h06a4308_0
  - aiohttp=3.9.3=py39h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - async-timeout=4.0.3=py39h06a4308_0
  - attrs=23.1.0=py39h06a4308_0
  - blas=1.0=openblas
  - blinker=1.6.2=py39h06a4308_0
  - brotli-python=1.0.9=py39h6a678d5_7
  - bzip2=1.0.8=h5eee18b_5
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.3.11=h06a4308_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - cairo=1.16.0=hb05425b_5
  - certifi=2024.2.2=py39h06a4308_0
  - cffi=1.16.0=py39h5eee18b_0
  - chardet=4.0.0=py39h06a4308_1003
  - click=8.1.7=py39h06a4308_0
  - cryptography=42.0.5=py39hdda0065_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.4.99=0
  - cuda-runtime=12.1.0=0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dbus=1.13.18=hb2f20db_0
  - eigen=3.4.0=hdb19cb5_0
  - expat=2.5.0=h6a678d5_0
  - ffmpeg=4.2.2=h20bf706_0
  - filelock=3.13.1=py39h06a4308_0
  - fontconfig=2.14.1=h4c34cd2_2
  - freetype=2.12.1=h4a9f257_0
  - frozenlist=1.4.0=py39h5eee18b_0
  - fsspec=2023.10.0=py39h06a4308_0
  - giflib=5.2.1=h5eee18b_3
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py39heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - google-auth=2.22.0=py39h06a4308_0
  - google-auth-oauthlib=0.5.2=py39h06a4308_0
  - graphite2=1.3.14=h295c915_1
  - grpc-cpp=1.48.2=he1ff14a_4
  - grpcio=1.48.2=py39he1ff14a_4
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - gtest=1.14.0=hdb19cb5_0
  - harfbuzz=4.3.0=hf52aaf7_1
  - hdf5=1.12.1=h2b7332f_3
  - huggingface_hub=0.20.3=py39h06a4308_0
  - icu=58.2=he6710b0_3
  - importlib-metadata=7.0.1=py39h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.3=py39h06a4308_0
  - jpeg=9e=h5eee18b_1
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.9.0.20=0
  - libcups=2.4.2=h2d74bed_1
  - libcurand=10.3.5.119=0
  - libcurl=8.5.0=h251f7ec_0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libllvm14=14.0.6=hdb19cb5_3
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libopenblas=0.3.21=h043d6bf_0
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.17=hdbd6064_0
  - libprotobuf=3.20.3=he621ea3_0
  - libssh2=1.10.0=hdbd6064_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h5eee18b_1
  - libxml2=2.10.4=hcbfbd50_0
  - libxslt=1.1.37=h2085143_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_0
  - markdown=3.4.1=py39h06a4308_0
  - markupsafe=2.1.3=py39h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py39h5eee18b_1
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py39h06a4308_0
  - multidict=6.0.4=py39h5eee18b_0
  - mysql=5.7.24=h721c034_2
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py39h06a4308_0
  - ninja=1.10.2=h06a4308_5
  - ninja-base=1.10.2=hd09550d_5
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numpy=1.26.4=py39heeff2f4_0
  - numpy-base=1.26.4=py39h8a23956_0
  - oauthlib=3.2.2=py39h06a4308_0
  - opencv=4.6.0=py39ha16400d_5
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.13=h7f8727e_0
  - packaging=23.2=py39h06a4308_0
  - pcre2=10.42=hebb0a14_0
  - pillow=10.2.0=py39h5eee18b_0
  - pip=23.3.1=py39h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - protobuf=3.20.3=py39h6a678d5_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyjwt=2.4.0=py39h06a4308_0
  - pyopenssl=24.0.0=py39h06a4308_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.18=h955ad1f_0
  - pytorch=2.2.0=cpu_py39hab5cca8_0
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.1=py39h5eee18b_0
  - qt-main=5.15.2=h7358343_9
  - qt-webengine=5.15.9=h9ab4d14_7
  - qtwebkit=5.212=h3fafdc1_5
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - regex=2023.10.3=py39h5eee18b_0
  - requests=2.31.0=py39h06a4308_1
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - safetensors=0.4.2=py39ha89cbab_0
  - setuptools=68.2.2=py39h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h5eee18b_0
  - sympy=1.12=py39h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tensorboard=2.12.1=py39h06a4308_0
  - tensorboard-data-server=0.7.0=py39h52d8a92_0
  - tensorboard-plugin-wit=1.8.1=py39h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - tokenizers=0.15.1=py39h22610ee_0
  - torchtriton=2.2.0=py39
  - tqdm=4.65.0=py39hb070fc8_0
  - transformers=4.37.2=py39h06a4308_0
  - typing-extensions=4.9.0=py39h06a4308_1
  - typing_extensions=4.9.0=py39h06a4308_1
  - tzdata=2024a=h04d1e81_0
  - werkzeug=2.3.8=py39h06a4308_0
  - wheel=0.41.2=py39h06a4308_0
  - x264=1!157.20191217=h7b6447c_0
  - xz=5.4.6=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.9.3=py39h5eee18b_0
  - zipp=3.17.0=py39h06a4308_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - charset-normalizer==3.3.2
      - einops==0.7.0
      - idna==3.6
      - nvidia-nccl-cu12==2.19.3
      - torch==2.2.1
      - torchaudio==2.1.1
      - torchvision==0.17.0
      - triton==2.2.0
      - urllib3==2.2.1
prefix: /home/ices/miniconda3/envs/STCCD
